### ISSUE TITLE
issue : 아벨이 안보이는 문제

### ISSUE THREAD

**Issue by plus100kt** [icepeng/articles#2]
## 문제
1. 아벨이 저번달부터 보이지 않습니다
2. 지식을 알려줄 사람이 적어졌습니다
3. 궁금한걸 물어볼 사람이 적어졌습니다.
4. 말할대상이 줄어들었습니다
5. 탁구 칠 대상이 멸종했습니다.

## 해결책
1. 고대로 가서 아벨을 데려옵니다

**Comment by icepeng** [comment]
머기업으로 만들어서 절 데려가시면 됩니다 'ㅅ'/

**Comment by 9j** [comment]
https://namu.wiki/w/%EA%B5%AC%EA%B8%80%EB%A7%81
